### ISSUE TITLE
Invalid detections on comments

### ISSUE THREAD

**Issue by Rizean** [Rizean/lp-builder#12]
warning: FILE: D:\other\LifePlay\LifePlay\Content\Modules\vin_Base\Quests\bggw\Scenes\bggw_episodes.lpscene  LINE: 17  WARN: INVALID_OPERAND - Repaired invalid operand: &&

line 17:     If stage == 1 // Ashley & Iris & Eric

**Comment by NickNo-dev** [comment]
you could simply strip everything from a line starting with the // before processing it.

**Comment by NickNo-dev** [comment]
The detection also is wrong for strings containing operand characters, so you have to ignore them as well *first*

**Comment by Rizean** [comment]
edge case normally ignore them will take a look

**Comment by Rizean** [comment]
also comments are fixed, I just for got to close it

**Comment by Rizean** [comment]
fixed
