### ISSUE TITLE
src and target parameters should be swapped

### ISSUE THREAD

**Issue by NickNo-dev** [Rizean/lp-builder#15]
Every command line command usually works with the paradigma SOURCE to TARGET
The builder currently swapps this:
`lpBuilder-win-x64.exe check <buildPath> <sourcePath>`
He requires TARGET from SOURCE.

**Comment by NickNo-dev** [comment]
Especially for the "check" variant a destination makes no sense...

**Comment by Rizean** [comment]
Agree will do after #11
