### ISSUE TITLE
builder touching all files

### ISSUE THREAD

**Issue by NickNo-dev** [Rizean/lp-builder#16]
I set the builder to build my complete pornempire folder.
This also contains readme.txt.

The readme was processed as well.
Line endings were converted to UNIX style. Empty lines removed.

TODO: Only process files that the builder should care for (lpscene, ...?) other files should just be copied without manipulations.

**Comment by Rizean** [comment]
this should be good but havent checked

**Comment by Rizean** [comment]
Closing based on:
```
NickNoToday at 12:25 PM
This time you nailed it...
```
