### ISSUE TITLE
relative paths not supported

### ISSUE THREAD

**Issue by NickNo-dev** [Rizean/lp-builder#17]
the builder does not work with relative paths

D:\Develop\NN\ModDev>..\lp-builder\dist\lpBuilder-win-x64.exe check null nn_HomeExpander\Scenes
Log Level: warning  logFile: build.log
buildPath: **D:\snapshot\lp-builder\src**\null
sourcePath: **D:\snapshot\lp-builder\src**\nn_HomeExpander\Scenes

**Comment by Rizean** [comment]
..\lp-builder\dist\lpBuilder-win-x64.exe check .\ nn_HomeExpander\Scenes

I've never seen null used as a relative path. That said there is a bug here.
