### ISSUE TITLE
Check If/ElseIf/Else/EndIf + nesting

### ISSUE THREAD

**Issue by NickNo-dev** [Rizean/lp-builder#2]
You can spend hours in finding falsely idented / written If clauses.
The builder could help a lot.

TODOs:
- Find "ElseIf" without condition -> Fatal Error (or correct to "ElseIf false")
- Find If / ElseIf / Else without EndIf
- Check+Correct identation of If / matching ElseIf / Else / EndIf

**Comment by Rizean** [comment]
I'm thinking my first pass at this will be check of the idents
